default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: /tmp

development:
  <<: *default
  database: view_component_reducible_dummy_development

test:
  <<: *default
  database: view_component_reducible_dummy_test

production:
  primary:
    <<: *default
    database: view_component_reducible_dummy_production
  cache:
    <<: *default
    database: view_component_reducible_dummy_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: view_component_reducible_dummy_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: view_component_reducible_dummy_production_cable
    migrations_paths: db/cable_migrate
